apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devops-automation-api
  title: DevOps Automation API
  description: |
    API REST Java com Spring Boot construída para ensinar automação DevOps com qualidade, 
    integração, CI/CD e containers. Fornece endpoints para consulta de CEP, informações de 
    sistema/container, health checks e demonstrações de integração com APIs externas. 
    Desenvolvida como parte do curso DevOps Automation com foco em práticas modernas de 
    desenvolvimento e deployment.
  tags:
    - java
    - java17
    - spring-boot
    - spring-boot-3
    - maven
    - rest-api
    - docker
    - devops
    - kubernetes
    - api-rest
    - thymeleaf
    - openapi
    - swagger
    - actuator
    - microservice
    - education
  annotations:
    github.com/project-slug: iesodias/devops-automation-api
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/iesodias/devops-automation-api
      title: Repositório GitHub
      icon: github
    - url: http://localhost:8081/swagger-ui.html
      title: Documentação API (Swagger UI)
      icon: docs
    - url: http://localhost:8081/actuator/health
      title: Health Check (Actuator)
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: team-devops
  system: devops-learning-platform
  providesApis:
    - devops-automation-api
  dependsOn:
    - resource:viacep-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: devops-automation-api
  description: API REST para automação e aprendizado DevOps com Spring Boot
  tags:
    - rest
    - openapi
    - java
  annotations:
    github.com/project-slug: iesodias/devops-automation-api
spec:
  type: openapi
  lifecycle: experimental
  owner: team-devops
  system: devops-learning-platform
  definition: |
    openapi: 3.0.1
    info:
      title: DevOps Automation API
      description: API REST Java Spring Boot para ensino de práticas DevOps
      version: 0.0.1-SNAPSHOT
    servers:
      - url: http://localhost:8081
        description: Servidor Local
    paths:
      /api/hello:
        get:
          summary: Hello básico
          operationId: hello
          responses:
            '200':
              description: Mensagem de saudação
              content:
                text/plain:
                  schema:
                    type: string
      /api/cep/{cep}:
        get:
          summary: Busca endereço a partir do CEP
          operationId: buscarEndereco
          parameters:
            - name: cep
              in: path
              required: true
              schema:
                type: string
                pattern: '\d{8}'
          responses:
            '200':
              description: Endereço encontrado
              content:
                application/json:
                  schema:
                    type: object
      /api/info:
        get:
          summary: Informações do container
          operationId: getContainerInfo
          responses:
            '200':
              description: Informações do container/sistema
              content:
                application/json:
                  schema:
                    type: object
      /actuator/health:
        get:
          summary: Health check da aplicação
          operationId: health
          responses:
            '200':
              description: Status da aplicação
              content:
                application/json:
                  schema:
                    type: object
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: viacep-api
  description: API externa ViaCEP para consulta de endereços brasileiros
  tags:
    - external-api
    - cep
    - brazil
spec:
  type: api
  owner: team-devops
  system: devops-learning-platform
